# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world
  print_var:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - context: Info # has an env_var called USER_NAME
      - run: echo $USER_NAME
     
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
  test-env-vars:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_var
